services:

  api:
    build: .
    container_name: lms-api
    ports:
    - "${BACK_END_HOST}:${BACK_END_PORT}:${BACK_END_PORT}"
    env_file:
    - .docker.env
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
